{% set name = "dpath" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1a7a0e6427d0a4156c792c82caf1f0109603f68ace792e36ca4596fd2cb8d9d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - dpath

about:
  home: https://www.github.com/akesterson/dpath-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Filesystem-like pathing and searching for dictionaries
  description: |
    A python library for accessing and searching dictionaries via /slashed/paths
    ala xpath. Basically it lets you glob over a dictionary as if it were a filesystem.
    It allows you to specify globs (ala the bash eglob syntax, through some advanced
    fnmatch.fnmatch magic) to access dictionary elements, and provides some
    facility for filtering those results.
  doc_url: https://github.com/akesterson/dpath-python
  dev_url: https://github.com/akesterson/dpath-python

extra:
  recipe-maintainers:
    - matthieujung
    - efiop
    - asford
