{% set name = "dpath" %}
{% set version = "2.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3380a77d0db4abf104125860ff6eb4bd07c97c65b81aad42a609717089a1bed0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - dpath

about:
  home: https://www.github.com/akesterson/dpath-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Filesystem-like pathing and searching for dictionaries
  description: |
    A python library for accessing and searching dictionaries via /slashed/paths
    ala xpath. Basically it lets you glob over a dictionary as if it were a filesystem.
    It allows you to specify globs (ala the bash eglob syntax, through some advanced
    fnmatch.fnmatch magic) to access dictionary elements, and provides some
    facility for filtering those results.
  doc_url: https://github.com/akesterson/dpath-python
  dev_url: https://github.com/akesterson/dpath-python

extra:
  recipe-maintainers:
    - matthieujung
    - efiop
    - asford
